#!/bin/bash

export CFLAGS='-g -O3 -fomit-frame-pointer -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_REENTRANT=1 -D_THREAD_SAFE=1 -D_LARGEFILE64_SOURCE=1'

./configure \
  --enable-gui=gtk2 \
  --enable-rubyinterp=yes \
  --enable-pythoninterp=yes \
  --enable-cscope \
  --with-features=huge \
  --with-compiledby='Sheldon Van Dyck <sheldon.dyck@gmail.com>'
