#!/bin/sh

update_git() {
  git_url=$1
  dir=$2
  echo "$dir"
  if [ -d "$dir" ]; then
    cd $dir
    git pull
    cd ..
  else
    git clone $git_url
  fi
}

update_git 'git://github.com/scrooloose/nerdtree.git', 'nerdtree'
update_git 'git://github.com/vim-scripts/UltiSnips.git', 'UltiSnips' 
update_git 'git://github.com/kchmck/vim-coffee-script.git', 'vim-coffee-script'
update_git 'git://github.com/tpope/vim-rails.git', 'vim-rails'
update_git 'git://github.com/tpope/vim-haml.git', 'vim-haml'
update_git 'git://github.com/tpope/vim-surround.git', 'vim-surround'
