#!/bin/sh

update_git() {
  echo $1
  cd $1
  git pull
  vim -c ":helptags $1/doc" -q 2> /dev/null
  cd ..
}

update_git 'nerdtree'
update_git 'vim-haml'
update_git 'vim-rails'
update_git 'vim-surround'
update_git 'zencoding-vim'
update_git 'snipmate.vim'
