#!/bin/sh

update_git() {
  git_url=$1
  dir=$2
  echo "$dir: $git_url"
  if [ -d "$dir" ]; then
    cd $dir
    git pull
    cd ..
  else
    git clone $git_url
  fi
}

update_git 'git://github.com/scrooloose/nerdtree.git' 'nerdtree'
update_git 'git://github.com/vim-scripts/UltiSnips.git' 'UltiSnips' 
update_git 'git://github.com/kchmck/vim-coffee-script.git' 'vim-coffee-script'
update_git 'git://github.com/mattn/zencoding-vim.git' 'zencoding-vim'
update_git 'git://github.com/tpope/vim-rails.git' 'vim-rails'
update_git 'git://github.com/tpope/vim-haml.git' 'vim-haml'
update_git 'git://github.com/tpope/vim-surround.git' 'vim-surround'
update_git 'git://github.com/millermedeiros/vim-statline.git' 'vim-statline'
update_git 'git://github.com/skammer/vim-css-color.git' 'vim-css-color'

update_git 'git://github.com/tpope/vim-pathogen.git' 'vim-pathogen'
#vim -c ":helptags $1/doc" -q 2> /dev/null
echo 'coping pathogen to autoload'
cp vim-pathogen/autoload/pathogen.vim ../autoload
